---
title: "Hi"
date: 2023-03-01
categories: [news]
engine: knitr
---

```{r}
print("Hello, world.")
```

Keeping a (technical) blog has been something I've thought of for quite a while.
I've usually been held back by my uncertainty over why someone would ever want to read a technical blog by me:
although I *know* plenty of things, I hardly have *in-depth* knowledge about anything, so I've always figured that there were people who were better at writing these things.
There are already so many blogs out there, and I often feel that I don't really want to add to the Huge Mess.

But I somehow managed to sign myself up at [work](https://www.turing.ac.uk/research-engineering) to make blog posts, so now I've got to do something.
Now, at work, I'm probably going to be writing about machine learning basics, and that's *hardly* a topic lacking on the Internet.
But---I suppose, the one thing I do know a fair bit about is chemistry, since that's what I've spent 8 years of my life studying.
I post a lot about chemistry [elsewhere](https://chemistry.stackexchange.com/users/16683/orthocresol?tab=answers&sort=votes), and on several occasions (in real life) I've had people tell me that they found my writeups useful.

So, maybe I'll intersperse my less-useful posts with some half-useful posts about chemistry...?
And even if nobody reads it, this is probably useful for myself anyway!
